### PR TITLE
Make headers self-sufficient

### PR DESCRIPTION
**Pull request by vlolteanu**

### CODE REVIEW

**Comment by vlolteanu** [comment]
Most of the headers don't make sense on their own, but instead rely on some other headers being included before them. Notably, IDEs have trouble parsing these offending header files.

**Comment by mrcook** [comment]
Hi @vlolteanu, thanks for the PR. Could you please let me know which IDEs have problems. I am using CLion which works fine with things as they currently are, and earlier last year I opened the project in Visual Studio, which also didn't have any issues.

**Comment by vlolteanu** [comment]
Hi, I was too hasty making a blanket statement about IDEs. The one I'm using is QtCreator and it doesn't try to look for missing types etc. in headers that are not explicitly included.

Self-sufficient headers are generally considered a best practice, and the ramifications go beyond eliciting good behavior from IDEs. A quick web search could explain things far better than I ever could.

Granted, the advantages of self-contained headers are less likely to come into play with a codebase that isn't expected to change significantly.

**Comment by mrcook** [comment]
For the long term you are correct, but for now I'd like to leave things as they are.

There are still a number of refactorings needed (modularise the game input code, load/save routines, inventory/equipment, etc.) and having all the includes in that `header.h` does make this process a little less painful.

Thanks, Michael.

**Pull request closed without merging**
